-- Datos de ejemplo SOLO para desarrollo local (npm run db:seed:local).
DELETE FROM patient_profiles; DELETE FROM patient_labs; DELETE FROM recommendations; DELETE FROM patient_logs; DELETE FROM portal_links;
DELETE FROM files; DELETE FROM consultations; DELETE FROM appointments; DELETE FROM patients; DELETE FROM memberships; DELETE FROM sessions; DELETE FROM businesses;
INSERT INTO businesses (id, name, slug, email, phone) VALUES ('b-paula', 'Consultorio Paula Restrepo', 'paula-restrepo', 'consultorio@ejemplo.com', '3001234567');
INSERT INTO businesses (id, name, slug) VALUES ('b-demo2', 'Nutrición Integral Demo', 'nutricion-demo');
INSERT INTO patients (id,business_id,first_name,last_name,sex,birth_date,height_cm,phone,goal) VALUES ('p-maria','b-paula','María','Gómez','F','1992-03-14',168,'3001112233','Bajar grasa y ganar músculo');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-maria-0','b-paula','p-maria','2026-05-08',82,36,24,NULL);
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-maria-0','b-paula','p-maria','2026-05-08T09:00','done','primera');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-maria-1','b-paula','p-maria','2026-06-05',80,34.5,24.8,NULL);
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-maria-1','b-paula','p-maria','2026-06-05T09:00','done','control');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-maria-2','b-paula','p-maria','2026-07-03',77.5,33,25.5,NULL);
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-maria-2','b-paula','p-maria','2026-07-03T09:00','done','control');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-maria-3','b-paula','p-maria','2026-08-07',75.5,31.5,26.3,NULL);
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-maria-3','b-paula','p-maria','2026-08-07T09:00','done','control');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-maria-4','b-paula','p-maria','2026-09-04',74,30,27,'{"cintura": 86, "cadera": 108, "pas": 118, "pad": 76, "glu": 92}');
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-maria-4','b-paula','p-maria','2026-09-04T09:00','done','control');
INSERT INTO appointments (id,business_id,patient_id,starts_at,kind) VALUES ('a-maria-next','b-paula','p-maria','2026-10-09T09:00','control');
INSERT INTO patients (id,business_id,first_name,last_name,sex,birth_date,height_cm,phone,goal) VALUES ('p-andres','b-paula','Andrés','Ruiz','M','1985-06-02',178,'3002223344','Bajar de peso, reducir azúcar');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-andres-0','b-paula','p-andres','2026-05-12',96,30,31,NULL);
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-andres-0','b-paula','p-andres','2026-05-12T09:00','done','primera');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-andres-1','b-paula','p-andres','2026-06-09',94,28.5,31.8,NULL);
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-andres-1','b-paula','p-andres','2026-06-09T09:00','done','control');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-andres-2','b-paula','p-andres','2026-07-07',92,27,32.5,NULL);
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-andres-2','b-paula','p-andres','2026-07-07T09:00','done','control');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-andres-3','b-paula','p-andres','2026-08-11',90.5,25.5,33.4,NULL);
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-andres-3','b-paula','p-andres','2026-08-11T09:00','done','control');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-andres-4','b-paula','p-andres','2026-09-08',89,24,34,'{"cintura": 98, "cadera": 104, "pas": 128, "pad": 84, "glu": 101}');
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-andres-4','b-paula','p-andres','2026-09-08T09:00','done','control');
INSERT INTO appointments (id,business_id,patient_id,starts_at,kind) VALUES ('a-andres-next','b-paula','p-andres','2026-10-07T10:30','control');
INSERT INTO patients (id,business_id,first_name,last_name,sex,birth_date,height_cm,phone,goal) VALUES ('p-laura','b-paula','Laura','Méndez','F','1999-01-20',160,'3003334455','Mantenimiento');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-laura-0','b-paula','p-laura','2026-05-15',56,25,26.5,NULL);
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-laura-0','b-paula','p-laura','2026-05-15T09:00','done','primera');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-laura-1','b-paula','p-laura','2026-06-12',55.5,24.5,27,NULL);
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-laura-1','b-paula','p-laura','2026-06-12T09:00','done','control');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-laura-2','b-paula','p-laura','2026-07-10',55,24,27.3,NULL);
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-laura-2','b-paula','p-laura','2026-07-10T09:00','done','control');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-laura-3','b-paula','p-laura','2026-08-14',55.2,23.5,27.8,NULL);
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-laura-3','b-paula','p-laura','2026-08-14T09:00','done','control');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-laura-4','b-paula','p-laura','2026-09-11',55,23,28,'{"cintura": 68, "cadera": 94}');
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-laura-4','b-paula','p-laura','2026-09-11T09:00','done','control');
INSERT INTO appointments (id,business_id,patient_id,starts_at,kind) VALUES ('a-laura-next','b-paula','p-laura','2026-10-14T16:00','control');
INSERT INTO patients (id,business_id,first_name,last_name,sex,birth_date,height_cm,phone,goal) VALUES ('p-carlos','b-paula','Carlos','Ortiz','M','1974-08-11',172,'3004445566','Controlar glucosa y grasa visceral');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-carlos-0','b-paula','p-carlos','2026-05-20',92,32,28.5,NULL);
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-carlos-0','b-paula','p-carlos','2026-05-20T09:00','done','primera');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-carlos-1','b-paula','p-carlos','2026-06-17',91,31.5,29,NULL);
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-carlos-1','b-paula','p-carlos','2026-06-17T09:00','done','control');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-carlos-2','b-paula','p-carlos','2026-07-15',90,30.5,29.3,NULL);
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-carlos-2','b-paula','p-carlos','2026-07-15T09:00','done','control');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-carlos-3','b-paula','p-carlos','2026-08-19',89,29.8,29.8,NULL);
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-carlos-3','b-paula','p-carlos','2026-08-19T09:00','done','control');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-carlos-4','b-paula','p-carlos','2026-09-16',88,29,30,'{"cintura": 104, "pas": 136, "pad": 88, "glu": 108}');
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-carlos-4','b-paula','p-carlos','2026-09-16T09:00','done','control');
INSERT INTO appointments (id,business_id,patient_id,starts_at,kind) VALUES ('a-carlos-next','b-paula','p-carlos','2026-10-03T11:00','control');
INSERT INTO patients (id,business_id,first_name,last_name,sex,birth_date,height_cm,phone,goal) VALUES ('p-jorge','b-paula','Jorge','Ramírez','M','1958-02-05',170,'3005556677','Cuidado renal, bajar grasa');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-jorge-0','b-paula','p-jorge','2026-05-15',85,31.5,28.5,NULL);
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-jorge-0','b-paula','p-jorge','2026-05-15T09:00','done','primera');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-jorge-1','b-paula','p-jorge','2026-06-12',84.2,31,28.8,NULL);
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-jorge-1','b-paula','p-jorge','2026-06-12T09:00','done','control');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-jorge-2','b-paula','p-jorge','2026-07-10',83.5,30.8,29,NULL);
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-jorge-2','b-paula','p-jorge','2026-07-10T09:00','done','control');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-jorge-3','b-paula','p-jorge','2026-08-14',82.8,30.4,29.2,NULL);
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-jorge-3','b-paula','p-jorge','2026-08-14T09:00','done','control');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg,fat_pct,muscle_pct,measures) VALUES ('c-jorge-4','b-paula','p-jorge','2026-09-15',82,30,29.5,'{"cintura": 102, "pas": 142, "pad": 86, "glu": 106}');
INSERT INTO appointments (id,business_id,patient_id,starts_at,status,kind) VALUES ('a-jorge-4','b-paula','p-jorge','2026-09-15T09:00','done','control');
INSERT INTO appointments (id,business_id,patient_id,starts_at,kind) VALUES ('a-jorge-next','b-paula','p-jorge','2026-10-03T15:30','control');
INSERT INTO patients (id,business_id,first_name,last_name,sex,phone) VALUES ('p-otro','b-demo2','Paciente','De Otro Negocio','F','3009998877');
INSERT INTO consultations (id,business_id,patient_id,date,weight_kg) VALUES ('c-otro','b-demo2','p-otro','2026-09-20',70);
INSERT INTO patient_profiles (patient_id,business_id,clinical) VALUES ('p-jorge','b-paula','{"lesiones": [{"z": "rodD", "n": "Artrosis", "lv": 1, "d": "2022"}, {"z": "lumbar", "n": "Hernia L4-L5", "lv": 2, "d": "2019"}], "riesgos": [{"k": "renal", "lv": 2, "nota": "Enfermedad renal 3a y potasio alto"}, {"k": "cv", "lv": 2, "nota": "Hipertensión, LDL alto y edad"}, {"k": "metab", "lv": 1, "nota": "Prediabetes y grasa visceral alta"}], "cond": [{"n": "Enfermedad renal crónica, estadio 3a", "d": "2024"}, {"n": "Hipertensión arterial", "d": "2015"}, {"n": "Prediabetes", "d": "2025"}], "meds": [{"n": "Losartán", "dosis": "50 mg", "h": "Mañana", "para": "Presión y protección del riñón"}, {"n": "Atorvastatina", "dosis": "20 mg", "h": "Noche", "para": "Colesterol"}, {"n": "Metformina", "dosis": "500 mg", "h": "Con el almuerzo", "para": "Prediabetes"}], "alergias": ["Intolerancia leve a la lactosa"], "antecedentes": ["Padre con infarto a los 70 años"], "habitos": ["Exfumador desde 2010", "Camina 20 minutos, 3 veces por semana"]}');
INSERT INTO patient_labs (id,business_id,patient_id,date,vals) VALUES ('l-jorge-0','b-paula','p-jorge','2026-03-12','{"col": 248, "ldl": 168, "hdl": 38, "tg": 220, "glu": 112, "hba1c": 6.2, "creat": 1.6, "tfg": 46, "k": 5.3, "vitd": 18}');
INSERT INTO patient_labs (id,business_id,patient_id,date,vals) VALUES ('l-jorge-1','b-paula','p-jorge','2026-09-10','{"col": 228, "ldl": 150, "hdl": 41, "tg": 190, "glu": 106, "hba1c": 6.0, "creat": 1.55, "tfg": 48, "k": 5.1, "vitd": 24}');
INSERT INTO recommendations (id,business_id,patient_id,text,created_at) VALUES ('r-jorge','b-paula','p-jorge','Moderemos la proteína y prefiere frutas bajas en potasio: manzana, pera, fresas y piña.','2026-09-15 15:00:00');
INSERT INTO recommendations (id,business_id,patient_id,text,created_at) VALUES ('r-maria','b-paula','p-maria','Vas muy bien: bajaste 8 kg en 4 meses. Mantén la proteína en el desayuno.','2026-09-04 15:00:00');
